### ISSUE TITLE
Etcd namespace prefix on get, but not on set function?

### ISSUE THREAD

**Issue by zivkovic** [kumuluz/kumuluzee-config#12]
Version: latest (1.2.0)

Just wondering if this is actually a bug, or what the reasoning behind this is.

Etcd2ConfigurationSource.java

**set(key, value)** function saves any key it gets. No namespace is prefixed to the key.
**get(key**) fetches the key, but always prefixes the key with namespace.

Is this a bug in the implementation?

Example:
```
etcd2ConfigurationSource.set("A.B.C", "value_a"); // Sets the key
etcd2ConfigurationSource.get("A.B.C"); // Gets the value, always Optional.empty()
```

**set** uses key "A/B/C"
**get** uses key "environments/dev/services/name/1.0.0-SNAPSHOT/config/A/B/C"

Could someone explain why this is implemented this way?

What I'm trying to do is save a value into etcd, and then fetch it for later processing using multiple microservices.

If this is actually missing, I can submit a PR to fix it asap.

Another question. Why does **configurationUtils.set(key, value)** always use the first configuration source in the list? If I want to set some key/value into etcd, I have to get Etcd2ConfigurationSource from **configurationUtil.getConfigurationSources()**, and then use the returned instance for any etcd2 manipulation.

Looking forward to any answer.

Best regards, Jan

**Comment by jmezna** [comment]
I fixed the implementation for _set_, now the namespace is correctly prefixed. 

The method configurationUtils.set(key, value) is just a draft and has never been finalised since there were no real use cases for it. If you have a use case and a solution, we can discuss it and include it into the KumuluzEE.

**Comment by zivkovic** [comment]
Okay, thanks for the confirmation it's actually a bug.

My use case is I want to save some config values into etcd. It might be good to always use etcd/consul configuration server to save config settings, if present. Or just a way to make configurationUtils use any of those two. If etcd/consul is not present, then save in some other configuration source meant for 'on the fly' configuration changes that do not persist (in memory configuration settings) or something along those lines.
